version: '3.4'

services:
  # mongodb:
  #   image: mongo:4.4
  #   container_name: app_mongo
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - data:/data/db
  redis:
    image: redis:latest
    container_name: app_redis
    env_file:
      - ./.env
    ports:
      - 6379:6379
    volumes:
      - data:/data/cache
  otpverifysignupapi:
    container_name: app
    image: otpverifysignupapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      # WAIT_HOSTS: app_mongo:27017
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

volumes:
  data:
